[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=native"]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
split-debuginfo = "packed"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    "-C",
    "target-cpu=native",
    "-C",
    "target-feature=+crt-static",
]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=native"]

[env]
RAYON_NUM_THREADS = "0"

[incremental]
enabled = true

[workspace]
resolver = "2"
