name: Cargo Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup Nix cache
      uses: cachix/cachix-action@v12
      with:
        name: devenv
        skipPush: true

    - name: Run cargo test in nix-shell
      run: nix-shell --run "cargo test"
